"""
SQL validation and security layer.

Every SQL query generated by Opus passes through this validator before
it can be executed. It blocks dangerous operations, enforces LIMIT clauses,
and checks basic syntax.

This is the last line of defense, if Opus hallucinates a DROP TABLE
or generates malformed SQL, this catches it.
"""

import re
import sqlparse

from core.config import Config


class SQLValidator:
    def __init__(self, config: Config):
        self.blocked = [p.upper() for p in config.security.get("blocked_sql_patterns", [])]
        self.require_limit = config.security.get("require_limit", True)
        self.default_limit = config.security.get("default_limit", 100)

    def validate(self, sql: str) -> dict:
        """
        Validate SQL against security rules and syntax.

        Returns:
            {
                "valid": bool,
                "errors": [...],      # Blockers — SQL must not be executed
                "warnings": [...],    # Non-fatal issues (e.g., LIMIT added)
                "cleaned_sql": str    # Possibly modified SQL
            }
        """
        result = {
            "valid": True,
            "errors": [],
            "warnings": [],
            "cleaned_sql": sql
        }
        sql_upper = sql.upper().strip()

        # Check 1: Blocked SQL keywords (DROP, DELETE, UPDATE, etc.)
        for pattern in self.blocked:
            # Word boundary match: catches "DROP TABLE" but not "dropped_at"
            if re.search(rf'\b{pattern}\b', sql_upper):
                result["valid"] = False
                result["errors"].append(f"Blocked SQL keyword: {pattern}")

        # Check 2: LIMIT clause required for non-aggregate queries
        has_agg = any(
            kw in sql_upper
            for kw in ["GROUP BY", "COUNT(", "SUM(", "AVG(", "MAX(", "MIN("]
        )
        if self.require_limit and "LIMIT" not in sql_upper and not has_agg:
            result["warnings"].append(
                f"No LIMIT clause — adding LIMIT {self.default_limit}"
            )
            result["cleaned_sql"] = (
                sql.rstrip().rstrip(";") + f"\nLIMIT {self.default_limit};"
            )

        # Check 3: Basic syntax validation 
        try:
            parsed = sqlparse.parse(sql)
            if not parsed or not parsed[0].tokens:
                result["valid"] = False
                result["errors"].append("Failed to parse SQL")
        except Exception as e:
            result["valid"] = False
            result["errors"].append(f"Parse error: {e}")

        # Check 4: Must be a read-only query 
        if not sql_upper.startswith("SELECT") and not sql_upper.startswith("WITH"):
            result["valid"] = False
            result["errors"].append("SQL must start with SELECT or WITH")

        return result